routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TypeController;
use App\Http\Controllers\PetController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main');
})->name('profile');;
Route::resource('types', TypeController::class);
Route::resource('pets', PetController::class);
Route::get('/create-pdf/{id}', [PetController::class, 'pdf']);

app/Models/Pet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Models\Type;

class Pet extends Model
{
    use  HasFactory ;


    protected $fillable = [
        'name',
        'description',
        'pol'
    ];


    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    public function type()
    {
        return $this->belongsTo(Type::class);
    }
}

app/Models/Type.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Models\Pet;

class Type extends Model
{
    use  HasFactory ;


    protected $fillable = [
        'name',
    ];


    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    public function pets()
    {
        return $this->hasMany(Pet::class);
    }

    public static function boot() {
        parent::boot();

        static::deleting(function($type) {
            $type->pets()->delete();

        });
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PetController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;
use App\Models\Type;
use App\Models\Pet;
use Flash;
use PDF;

/**
 * Class PetController
 * @package App\Http\Controllers
 */
class PetController extends Controller
{
    /**
     * @param Request $request
     * @return mixed
     */
    public function index(Request $request)
    {

        $pets = Pet::orderBy('name')->get();
        return view('pets.index', compact('pets'));
    }

    /**
     * @return mixed
     */
    public function create()
    {

        $types = Type::orderBy('name')->get()->pluck('name', 'id');
        return view('pets.create', compact('types'));
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'type_id' => 'required',
        ]);

        $pet = new Pet;
        $pet->name = $request->name;
        $pet->type_id = $request->type_id;
        $pet->pol = $request->pol;
        $pet->description = $request->description;
        $pet->save();

        return redirect(route('pets.index'))->with('message', 'Животное добавлено!');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function edit($id)
    {
        $pet = Pet::findOrFail($id);
        $types = Type::orderBy('name')->get()->pluck('name', 'id');
        return view('pets.edit', compact('pet', 'types'));
    }


    /**
     * @param Request $request
     * @param $id
     * @return mixed
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'type_id' => 'required',
        ]);
        $pet = Pet::findOrFail($id);
        $pet->name = $request->name;
        $pet->type_id = $request->type_id;
        $pet->pol = $request->pol;
        $pet->description = $request->description;
        $pet->update();

        return redirect(route('pets.index'))->with('message', 'Животное было изменено!');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function show($id)
    {
        $pet = Pet::findOrFail($id);
        return view('pets.show', compact('pet'));
    }
    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        $pet = Pet::findOrFail($id);

        $pet->destroy($id);
        return redirect(route('pets.index'))->with('message', 'Животное было удалено!');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function pdf($id)
    {
        $pet = Pet::findOrFail($id);

        $data = [
            'name' => $pet->name ,
            'pol' => $pet->pol ,
            'type' => $pet->type->name,
            'description' =>  $pet->description
        ];

        $pdf = PDF::loadView('pets.pdf', $data);


        return $pdf->stream('pet.pdf');

     //   return $pdf->download('pet.pdf');
    }
}

app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;
use App\Models\Type;
use Flash;


/**
 * Class TypeController
 * @package App\Http\Controllers
 */
class TypeController extends Controller
{
    /**
     * @param Request $request
     * @return mixed
     */
    public function index(Request $request)
    {

       // phpinfo();
      $types = Type::orderBy('name')->get();
      return view('types.index', compact('types'));
    }

    /**
     * @return mixed
     */
    public function create()
    {

        return view('types.create');
    }

    /**
     * @param Request $request
     * @return mixed
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);

        $type = new Type;
        $type->name = $request->name;
        $type->save();

        return redirect(route('types.index'))->with('message', 'Тип добавлен!');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function edit($id)
    {
        $type = Type::findOrFail($id);
        return view('types.edit', compact('type'));
    }


    /**
     * @param Request $request
     * @param $id
     * @return mixed
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $type = Type::findOrFail($id);
        $type->name = $request->name;
        $type->update();

        return redirect(route('types.index'))->with('message', 'Тип был изменен!');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        $type = Type::findOrFail($id);

        $type->destroy($id);
        return redirect(route('types.index'))->with('message', 'Тип был удален!');
    }
}

resources/views/layouts/page.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Программа регистрация животных</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <script src="{{ asset('/assets/js/app.js') }}" defer></script>
    <link href="{{ asset('/assets/css/style.css') }}" rel="stylesheet">
</head>
<body>

<div class="pb-5 app">
    <div class="px-5 py-2 title" >
        <a href="/"><h4 class=" ">Программа регистрации животных, <br> поступивших в приют</h4></a>
    </div>
   <div class="container">
       <div class="col-lg-12">
           @yield('content')
       </div>
   </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

resources/views/main.blade.php
@extends('layouts.page')

@section('content')
        <div class="row d-flex justify-content-center" style="padding-top:20vh">
            <div class="col-lg-4">
                <a href="{{route('types.index')}}">
                    <div class="card card-bl py-5 px-3">
                        <h5 class="text-center">Тип животных</h5>
                    </div>
                </a>
            </div>
            <div class="col-lg-4">
                <a href="{{route('pets.index')}}">
                    <div class="card card-bl py-5 px-3">
                        <h5 class="text-center">Список поступивших животных</h5>
                    </div>
                </a>
            </div>
        </div>

@endsection

resources/views/pets/create.blade.php
@extends('layouts.page')

@section('content')

    <div class="py-5">
        <h4>Добавление нового животного </h4>
    </div>
    
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card py-5 px-5">
                @if (count($types)>0)
                    {!! Form::open(['route' => 'pets.store', 'method' => 'POST']) !!}
                    <div class="mb-3">
                        <label  class="form-label" for="name">Имя<span class="text-danger">*</span></label>
                        <?php  if ($errors->has('name')) $erName = true; ?>
                        {!!  Form::text('name', null, ['class' =>   isset($erName) ? 'form-control is-invalid ' : 'form-control', 'id' => 'name']) !!}
                        @if ($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <label  class="form-label" for="type">Тип<span class="text-danger">*</span></label>
                        <?php  if ($errors->has('type_id')) $erType= true; ?>
                        {!!  Form::select('type_id', $types, null, ['placeholder' => 'Выберите значение', 'class' =>   isset($erType) ? 'form-select is-invalid ' : 'form-select', 'id' => 'type']) !!}
                        @if ($errors->has('type_id'))
                            <span class="text-danger">{{ $errors->first('type_id') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <div class="form-check form-check-inline pe-5">
                            <input class="form-check-input" type="radio" name="pol" value="F" id="flexRadioDefault1" checked>
                            <label class="form-check-label" for="flexRadioDefault1">
                                Девочка
                            </label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="pol" value="M" id="flexRadioDefault2" >
                            <label class="form-check-label" for="flexRadioDefault2">
                                Мальчик
                            </label>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label  class="form-label" for="description">Описание</label>
                        {!!  Form::textarea('description', null, ['class' =>   'form-control', 'id' => 'description']) !!}

                    </div>
                    <div class="text-center">
                        <a href="{{route('pets.index')}}" class="btn btn-light">Отменить</a>
                        <button type="submit" class="btn btn-secondary">Добавить</button>
                    </div>
                    {!! Form::close() !!}
                @else
                    Отсутствуют типы. <a href="{{ route('types.create') }}">Добавьте</a> хотя бы один тип.
                @endif

            </div>
        </div>
    </div>

@endsection

resources/views/pets/edit.blade.php
@extends('layouts.page')

@section('content')

    <div class="py-5">
        <h4>Добавление нового животного </h4>
    </div>
    <div class="mb-5">
        <a href="/"><i class="las la-arrow-circle-left"></i>Вернуться назад</a>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card py-5 px-5">
                @if (count($types)>0)
                    {{ Form::model($pet, ['route' => ['pets.update', $pet->id], 'method' => 'PATCH'])}}
                    <div class="mb-3">
                        <label  class="form-label" for="name">Имя<span class="text-danger">*</span></label>
                        <?php  if ($errors->has('name')) $erName = true; ?>
                        {!!  Form::text('name', null, ['class' =>   isset($erName) ? 'form-control is-invalid ' : 'form-control', 'id' => 'name']) !!}
                        @if ($errors->has('name'))
                            <span class="text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <label  class="form-label" for="type">Тип<span class="text-danger">*</span></label>
                        <?php  if ($errors->has('type_id')) $erType= true; ?>
                        {!!  Form::select('type_id', $types, null, ['placeholder' => 'Выберите значение', 'class' =>   isset($erType) ? 'form-select is-invalid ' : 'form-select', 'id' => 'type']) !!}
                        @if ($errors->has('type_id'))
                            <span class="text-danger">{{ $errors->first('type_id') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <div class="form-check form-check-inline pe-5">
                            <input class="form-check-input" type="radio" name="pol" value="F" id="flexRadioDefault1" @if ($pet->pol=='F') checked @endif>
                            <label class="form-check-label" for="flexRadioDefault1">
                                Девочка
                            </label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="pol" value="M" id="flexRadioDefault2" @if ($pet->pol=='M') checked @endif>
                            <label class="form-check-label" for="flexRadioDefault2">
                                Мальчик
                            </label>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label  class="form-label" for="description">Описание</label>
                        {!!  Form::textarea('description', null, ['class' =>   'form-control', 'id' => 'description']) !!}

                    </div>
                    <div class="text-center">
                        <a href="{{route('pets.index')}}" class="btn btn-light">Отменить</a>
                        <button type="submit" class="btn btn-secondary">Изменить</button>
                    </div>
                    {!! Form::close() !!}
                @else
                    Отсутствуют типы. <a href="{{ route('types.create') }}">Добавьте</a> хотя бы один тип.
                @endif

            </div>
        </div>
    </div>

@endsection

resources/views/pets/index.blade.php
@extends('layouts.page')

@section('content')

    <div class="py-5 d-flex justify-content-between">
        <h4>Список поступивших животных </h4>
        <a href="{{route('pets.create')}}" class="btn btn-outline-secondary"> <i class="las la-plus"></i> Добавить</a>
    </div>
    <div class="mb-5">
        <a href="/"><i class="las la-arrow-circle-left"></i>Вернуться назад</a>
    </div>
    @if (session('message'))
        <div class="alert alert-success my-3 px-2">
            {{ session('message') }}
        </div>
    @endif

    @if (count($pets)>0)
        <div class="card p-4">
            <table class="table">

                <tbody>

                @foreach ($pets as $pet)
                    <tr>
                        <td>{{ $pet->name }}</td>
                        <td style="width:250px">
                            <a class="btn btn-outline-primary" href="{{ route('pets.show', $pet->id) }}" title="Просмотр"><i class="las la-eye"></i></a>
                            <a class="btn btn-outline-warning" href="/create-pdf/{{$pet->id }}" title="Печать" target="_blank"><i class="las la-print"></i></a>
                            <a class="btn btn-outline-success" href="{{ route('pets.edit', $pet->id) }}" title="Изменить"><i class="las la-edit"></i></a>
                            <form method="POST" action="{{ route('pets.destroy', $pet->id) }}" style="display:inline-block;">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}

                                <button onclick="return confirm('Вы уверены, что хотите удалить?')" type="submit" class="btn btn-outline-danger" title="Удалить" ><i class='las la-trash'></i> </button>

                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    @endif
@endsection

resources/views/pets/pdf.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>{{ $name }}</title>
    <style>body { font-family: DejaVu Sans }</style>
</head>
<body>
<h3 class="card-title mb-4">{{ $name }}</h3>
<p class="card-text">
    <b>Тип:</b> {{ $type }} <br>
    <b>Пол:</b> @if ($pol=='F') Девочка @else Мальчик @endif <br>
    {!! nl2br(e($description)) !!}
</p>
</body>
</html>

resources/views/pets/show.blade.php
@extends('layouts.page')

@section('content')
    <div class="py-5">
        <div class="card py-5 px-5">
            <div class="card-body">
               <div class="">
                   <h5 class="card-title mb-4">{{ $pet->name }}</h5>
                   <p class="card-text">
                       <b>Тип:</b> {{ $pet->type->name }} <br>
                       <b>Пол:</b> @if ($pet->pol=='F') Девочка @else Мальчик @endif <br>
                       {!! nl2br(e($pet->description)) !!}
                   </p>
               </div>
                <div class="mt-5 pt-5">
                    <a href="{{route('pets.index')}}"><i class="las la-arrow-circle-left"></i>Вернуться назад</a>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/types/create.blade.php
@extends('layouts.page')

@section('content')

    <div class="py-5">
        <h4>Добавление нового типа животных </h4>
    </div>
    
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card py-5 px-5">
                {!! Form::open(['route' => 'types.store', 'method' => 'POST']) !!}
                <div class="mb-3">
                    <label  class="form-label" for="name">Название<span class="text-danger">*</span></label>
                    <?php  if ($errors->has('name')) $erName = true; ?>
                    {!!  Form::text('name', null, ['class' =>   isset($erName) ? 'form-control is-invalid ' : 'form-control', 'id' => 'name']) !!}
                    @if ($errors->has('name'))
                        <span class="text-danger">{{ $errors->first('name') }}</span>
                    @endif
                </div>
                <div class="text-center">
                    <a href="{{route('types.index')}}" class="btn btn-light">Отменить</a>
                   <button type="submit" class="btn btn-secondary">Добавить</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>

@endsection

resources/views/types/edit.blade.php
@extends('layouts.page')

@section('content')

    <div class="py-5">
        <h4>Изменение типа животных </h4>
    </div>
    <div class="mb-5">
        <a href="/"><i class="las la-arrow-circle-left"></i>Вернуться назад</a>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card py-5 px-5">
                {{ Form::model($type, ['route' => ['types.update', $type->id], 'method' => 'PATCH'])}}
                <div class="mb-3">
                    <label  class="form-label" for="name">Название<span class="text-danger">*</span></label>
                    <?php  if ($errors->has('name')) $erName = true; ?>
                    {!!  Form::text('name', null, ['class' =>   isset($erName) ? 'form-control is-invalid ' : 'form-control', 'id' => 'name']) !!}
                    @if ($errors->has('name'))
                        <span class="text-danger">{{ $errors->first('name') }}</span>
                    @endif
                </div>
                <div class="text-center">
                    <a href="{{route('types.index')}}" class="btn btn-light">Отменить</a>
                    <button type="submit" class="btn btn-secondary">Изменить</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>

@endsection

resources/views/types/index.blade.php
@extends('layouts.page')

@section('content')

    <div class="py-5 d-flex justify-content-between">
        <h4>Типы животных </h4>
        <a href="{{route('types.create')}}" class="btn btn-outline-secondary"> <i class="las la-plus"></i> Добавить</a>
    </div>
    <div class="mb-5">
        <a href="/"><i class="las la-arrow-circle-left"></i>Вернуться назад</a>
    </div>
    @if (session('message'))
        <div class="alert alert-success my-3 px-2">
            {{ session('message') }}
        </div>
    @endif

    @if (count($types)>0)
        <div class="card p-4">
            <table class="table">

                <tbody>

                @foreach ($types as $type)
                    <tr>
                        <td>{{ $type->name }}</td>
                        <td style="width:150px">
                            <a class="btn btn-outline-success" href="{{ route('types.edit', $type->id) }}" title="Изменить"><i class="las la-edit"></i></a>
                            <form method="POST" action="{{ route('types.destroy', $type->id) }}" style="display:inline-block;">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <button onclick="return confirm('Вы уверены, что хотите удалить?При удалении типа удалятся и все связанные животные!')" type="submit" class="btn btn-outline-danger" title="Удалить" ><i class='las la-trash'></i> </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    @endif
@endsection